#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$TMPDIR/gate-resource-request
cat > $payload <&0

gate=$(jq -r '.source.gate // ""' < $payload)
version=$(jq -r '.version // {}' < $payload)

# extract git configuration and pass it to git resource
git_source=$(cat "$payload" | jq -r .source.git)
git_payload=$(echo '{ "source": '$git_source', "version": '$version' }' | jq -r)

# only watch the gate pathch
git_payload=$(echo "$git_payload" | jq -r '.source.paths = ["'$gate'"]')
git_payload=$(echo "$git_payload" | jq -r '.source.ignore_paths = ["'**.autoclose'"]')

# forward to git-resource to let it do its checking
echo "$git_payload" | /opt/git-resource/check "$@" >&3