#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/gate-resource-request.XXXXXX)
cat > $payload <&0

# parse parameters
version=$(jq -r '.version' < $payload)
gate=$(jq -r '.version.gate // ""' < $payload)
passed=$(jq -r '.version.passed // ""' < $payload)

# extract git configuration and pass it to git resource
git_source=$(cat "$payload" | jq -r .source.git)
git_payload=$(echo '{ "source": '$git_source' }' | jq -r)

# forward to git-resource to let it fetch the repository, we always fetch at HEAD
git_out=$(echo "$git_payload" | /opt/git-resource/in $destination)
git_meta=$(echo $git_out | jq -r .metadata)

# write passed file
echo "$passed" > $destination/.git/gate_passed

jq -n "{
  version: $version,
  metadata: $git_meta
}" >&3
